/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gandalf.views;

import gandalf.models.Image;
import gandalf.models.MagicItem;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Caio
 */
public class View extends javax.swing.JFrame {

    private DefaultListModel<MagicItem> listModel;

    /**
     * Creates new form View
     */
    public View() {
        listModel = new DefaultListModel<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        showItemButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        nameTextField = new javax.swing.JTextField();
        elementComboBox = new javax.swing.JComboBox<>();
        weaponComboBox = new javax.swing.JComboBox<>();
        statsLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        elementImageLabel = new javax.swing.JLabel();
        elementLabel = new javax.swing.JLabel();
        weaponImageLabel = new javax.swing.JLabel();
        weaponLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gandalf");
        setSize(new java.awt.Dimension(815, 635));
        getContentPane().setLayout(null);

        listButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        listButton.setText("List");
        getContentPane().add(listButton);
        listButton.setBounds(690, 410, 100, 25);

        clearButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        getContentPane().add(clearButton);
        clearButton.setBounds(560, 410, 100, 25);

        saveButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        saveButton.setText("Save");
        getContentPane().add(saveButton);
        saveButton.setBounds(420, 410, 100, 25);

        showItemButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        showItemButton.setText("Show Item");
        getContentPane().add(showItemButton);
        showItemButton.setBounds(290, 410, 100, 25);

        jList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jList.setModel(listModel);
        scrollPane.setViewportView(jList);

        getContentPane().add(scrollPane);
        scrollPane.setBounds(290, 440, 500, 150);

        nameTextField.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        getContentPane().add(nameTextField);
        nameTextField.setBounds(550, 170, 170, 26);

        elementComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        elementComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Fire", "Water", "Earth", "Holy", "Dark" }));
        getContentPane().add(elementComboBox);
        elementComboBox.setBounds(320, 170, 160, 20);

        weaponComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        weaponComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Sword", "Magic Sword", "Double Sword", "Staff", "Bow", "Hammer", "Dagger", "Rapier" }));
        getContentPane().add(weaponComboBox);
        weaponComboBox.setBounds(80, 170, 160, 20);

        statsLabel.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        statsLabel.setForeground(new java.awt.Color(255, 255, 255));
        statsLabel.setText("<html>\nPower: Prominance<br>\nDamage: 312<br>\nAtkSpeed: 3\n</html>");
        getContentPane().add(statsLabel);
        statsLabel.setBounds(550, 210, 240, 63);

        nameLabel.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name your weapon");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(550, 130, 175, 28);

        elementImageLabel
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/gandalf/images/elements/fire.png"))); // NOI18N
        getContentPane().add(elementImageLabel);
        elementImageLabel.setBounds(350, 250, 100, 93);

        elementLabel.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        elementLabel.setForeground(new java.awt.Color(255, 255, 255));
        elementLabel.setText("Pick your element");
        getContentPane().add(elementLabel);
        elementLabel.setBounds(320, 130, 162, 28);

        weaponImageLabel
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/gandalf/images/weapons/sword.png"))); // NOI18N
        getContentPane().add(weaponImageLabel);
        weaponImageLabel.setBounds(60, 210, 200, 225);

        weaponLabel.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        weaponLabel.setForeground(new java.awt.Color(255, 255, 255));
        weaponLabel.setText("Pick your weapon");
        getContentPane().add(weaponLabel);
        weaponLabel.setBounds(80, 130, 161, 28);

        titleLabel.setFont(new java.awt.Font("Poor Richard", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Build Magic Items");
        titleLabel.setToolTipText("");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(240, 40, 326, 55);

        backgroundLabel.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/gandalf/images/background/background_02.png"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    public void WeaponComboBoxChange(MagicItem magicItem, Image image) {
        weaponImageLabel.setIcon(image.getWeaponImages()[weaponComboBox.getSelectedIndex()]);
        statsLabel.setText("<html>Power: " + magicItem.getPower() + "<br>Damage: " + magicItem.getDamage()
                + "<br>AtkSpeed: " + magicItem.getAtkSpeed() + "</html>");
    }

    public void ElementComboBoxChange(MagicItem magicItem, Image image) {
        elementImageLabel.setIcon(image.getElementImages()[elementComboBox.getSelectedIndex()]);
        statsLabel.setText("<html>Power: " + magicItem.getPower() + "<br>Damage: " + magicItem.getDamage()
                + "<br>AtkSpeed: " + magicItem.getAtkSpeed() + "</html>");
    }

    public MagicItem getMagicItem() {
        MagicItem magicItem = new MagicItem(weaponComboBox.getSelectedIndex(), elementComboBox.getSelectedIndex(),
                nameTextField.getText(), weaponComboBox.getItemAt(weaponComboBox.getSelectedIndex()),
                elementComboBox.getItemAt(elementComboBox.getSelectedIndex()));
        return magicItem;
    }

    public void showMagicItem(MagicItem magicItem) {
        listModel.addElement(magicItem);
    }

    public int confirm(MagicItem magicItem) {
        String text;

        text = "Are you sure you want to save this weapon?" + "\n\n" + magicItem.getWeapon() + " with "
                + magicItem.getElement() + " element" + "\nPower: " + magicItem.getPower() + "\nDamage: "
                + magicItem.getDamage() + "\nAtkSpeed: " + magicItem.getAtkSpeed() + "\n\n";

        return JOptionPane.showConfirmDialog(null, text);
    }

    public void clearList() {
        listModel.clear();
    }

    public void listFromDB(MagicItem magicItem) {
        listModel.addElement(magicItem);
    }

    public void addWeaponComboBoxListener(ItemListener il) {
        weaponComboBox.addItemListener(il);
    }

    public void addElementComboBoxListener(ItemListener il) {
        elementComboBox.addItemListener(il);
    }

    public void addShowItemListener(ActionListener al) {
        showItemButton.addActionListener(al);
    }

    public void addSaveListener(ActionListener al) {
        saveButton.addActionListener(al);
    }

    public void addClearListaListener(ActionListener al) {
        clearButton.addActionListener(al);
    }

    public void addListDBListener(ActionListener al) {
        listButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> elementComboBox;
    private javax.swing.JLabel elementImageLabel;
    private javax.swing.JLabel elementLabel;
    private javax.swing.JList<MagicItem> jList;
    private javax.swing.JButton listButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton showItemButton;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> weaponComboBox;
    private javax.swing.JLabel weaponImageLabel;
    private javax.swing.JLabel weaponLabel;
    // End of variables declaration//GEN-END:variables
}
